### ISSUE TITLE
Does font weight support ?

### ISSUE THREAD

**Issue by M-Adoo** [alexheretic/glyph-brush#111]
I try to use this library in my project,  and encountered some problems:

1. Does font weight or italic will be supported? Maybe italic can use a matrix to map. 
2. Can I stroke text ?

**Comment by alexheretic** [comment]
Bold/italic fonts are expected to be supplied as separate fonts ie _OpenSans-Italic.ttf,  Exo2-Light.otf_. Glyph brush does support multiple fonts in a single section.

Strike-through is not supported directly. I'm not 100% on how it's normally implemented but it might be possible to do so already for `glyph_brush` wrappers. `gfx-glyph` wrapper that lives in this repo does _not_ support doing this now so it could be used to experiment with support.

I'd see this kind of thing living in the `extra` generic data field as it doesn't impact layout in general.

**Comment by M-Adoo** [comment]
Thank you for your reply.  I get it.

**Comment by dhardy** [comment]
FYI a higher-level text layout library is needed here: [kas-text](https://github.com/kas-gui/kas-text) now supports the above while still using `glyph-brush` for rendering.
