### ISSUE TITLE
`glyphs` method not skip space char

### ISSUE THREAD

**Issue by M-Adoo** [alexheretic/glyph-brush#112]
I try to use glyphs to get how many char will be drawable, but found  invisible glyphs also returned. Does this is a bug, or that is what your expect ?

```rust
let sec = Section::default().add_text(Text::new("Nice to meet you!"));
let count = brush.glyphs().count():
```
Get count 17, not 14.

**Comment by alexheretic** [comment]
Yep that is expected. See [layout/CHANGELOG.md](https://github.com/alexheretic/glyph-brush/blob/master/layout/CHANGELOG.md#unreleased). I've now also included this in glyph_brush's changelog (c3ef50b3ec14ac22bf9ea8bac3cd69a149c60974).

**Comment by M-Adoo** [comment]
Thank you for your quick response，it's seems there isn's public api to know if a glyph will drawable ? I want know how many glyphs will be drawn.

**Comment by alexheretic** [comment]
That isn't provided by glyph_brush no. In general a glyph is drawable if it has an outline, so outlining the glyph determines this which isn't super cheap (part of the reason it's no longer used to layout text).

You could:
* Check if the char [is whitespace](https://doc.rust-lang.org/std/primitive.char.html#method.is_whitespace) which is not very sophisticated but very fast.
* [Outline the glyph](https://docs.rs/ab_glyph/0.2.1/ab_glyph/trait.Font.html#tymethod.outline) and see if there isn't any outline, somewhat expensive but maybe fast enough for your use case.

It's technically possible that **after** running `cache_queued` glyph_brush could have something like `brush.was_cached(font_id: FontId, glyph: &Glyph) -> bool` method. _false_ meaning either it wasn't queued at all, or it's a glyph that's invisible. This would be pretty fast. Would that be helpful?

**Comment by M-Adoo** [comment]
Yes, `brush.was_cached` is what I wanted.

**Comment by alexheretic** [comment]
Cool let me know if #113 looks ok to you. I went with `is_cached`, as it seemed better.

**Comment by M-Adoo** [comment]
Great! It's work for me.
