### ISSUE TITLE
Potential incorrect linebreaks between styles.

### ISSUE THREAD

**Issue by mooman219** [alexheretic/glyph-brush#117]
For sections of text with styling that can change part**way** through the word, it looks like from the code that a linebreak can be generated between the style changes. Also, the LineBreakIterator won't maintain break state between the two sections either which may break in some languages. xi_unicode::LineBreakLeafIter is meant to handle this situation (and also ropes in general).

**Comment by alexheretic** [comment]
There are some workarounds in place to prevent such issues, for example see the `eol_new_line_hard_breaks()` test which ensures eol hard breaks don't cause issue.

Switching to a multi-part aware line break iter sounds like an improvement though, I'll have to check out that out thanks.

**Comment by alexheretic** [comment]
I've updated xi-unicode but workarounds are still necessary. I'll close this for now and deal with any concrete bugs as they appear in their own tickets.

**Comment by mooman219** [comment]
Sounds good, thanks you!
