### ISSUE TITLE
Handle multiple draws per frame better

### ISSUE THREAD

**Issue by alexheretic** [alexheretic/glyph-brush#128]
Currently a `GlyphBrush` should call `process_queued` once per frame for the caching system to work properly. Multiple draws can be handled with multiple `GlyphBrush` each drawing once per frame.

We could probably do better here though.

**Comment by Nuckal777** [comment]
Didn't look deeply into the topic. Can we achieve better cache usage with multiple draws, if the user calls `GlyphBrush::cleanup_frame()` explicitly when finishing a frame? Currently the cache is trimmed after each draw implicitly.

**Comment by alexheretic** [comment]
Moved to more concrete issues #157 & #158
