### ISSUE TITLE
glyph_brush_layout: Right-Aligned Whitespace Ignored

### ISSUE THREAD

**Issue by anlumo** [alexheretic/glyph-brush#130]
When layouting text in right-aligned paragraphs, space characters on the right do not change the layout in any way.

It works with spaces on the left in left-aligned paragraphs.

![image](https://user-images.githubusercontent.com/644763/108274062-b151b880-7174-11eb-835f-714e1b77eb90.png)

Green text is:
```
<sp><sp>Left
Aligned
```

Blue text is:
```
Right<sp><sp>
Aligned
```

With `<sp>` being ASCII space (0x20).

**Comment by alexheretic** [comment]
It is deliberate that the built in layout will drop spaces between lines, otherwise the space would cause words to bump out of the align bound in some cases and it would look wrong.

So just including the trailing space in a word would be wrong, but maybe the current method could be improved / made more standard. Can you provide some more detailed examples of how other layout engines handle this?

**Comment by anlumo** [comment]
I should have mentioned that this is not an automatic line break, that's a manual one. I'm not limiting the bounds on either axis.

**Comment by alexheretic** [comment]
Ah yes that's an interesting distinction that isn't considered by the logic at the moment. 

So I think if other layout engines handle right-aligned `Foo \nbar` with the space jutting the "Foo" out then glyph-brush probably should too.

**Comment by anlumo** [comment]
Wordpad:
![image](https://user-images.githubusercontent.com/644763/108389287-d1828580-720f-11eb-9df1-5be3f71b42b3.png)

Affinity Designer:
![image](https://user-images.githubusercontent.com/644763/108389511-08f13200-7210-11eb-953f-1dc4abe0d6dc.png)

Froala (aka a Chrome [contenteditable](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content)):
![image](https://user-images.githubusercontent.com/644763/108389685-3342ef80-7210-11eb-912c-b128a916dddd.png)

Autodesk Fusion 360:
![image](https://user-images.githubusercontent.com/644763/108390118-9f255800-7210-11eb-80a9-af94895143b7.png)

So, so far it's 1/4 on the text layouting engines I have access to right now…

**Comment by alexheretic** [comment]
Thanks for investigating. So there's some inconsistency here it seems.

I'll also add that GIMP will ignore spaces when bound-wrapping `Foo bar` in the same way as glyph-brush, but will respect the space in `Foo \nbar`
![](https://user-images.githubusercontent.com/2331607/108408037-7905b500-721c-11eb-9cba-59e18b1d2cea.png)

My current thinking is that as long as it only affects explicit hard breaks it probably won't be any harm for glyph-brush to act this way too (assuming it won't be horrible to implement).

**Comment by alexheretic** [comment]
GIMP's method seem to be it'll ignore 1 space and 1 space only.

`Foo<sp>bar`
![](https://user-images.githubusercontent.com/2331607/108409381-11e90000-721e-11eb-9e6e-cdd8e76974f3.png)

`Foo<sp><sp>bar`
![](https://user-images.githubusercontent.com/2331607/108409410-1b726800-721e-11eb-8dbe-224edb181fee.png)

`Foo<sp><sp><sp>bar`
![](https://user-images.githubusercontent.com/2331607/108409429-20cfb280-721e-11eb-9f81-ccf088869f15.png)

**Comment by anlumo** [comment]
LibreOffice does show the extra spaces:
![image](https://user-images.githubusercontent.com/644763/108409809-f20a0a00-7226-11eb-9021-3a70fa44f309.png)

It's really wild that there's such a difference between text layout engines. I have no idea which one is “correct”…

**Comment by alexheretic** [comment]
I've implemented one take to handle `Foo bar` & `Foo \nbar` differently (#131). I'm just not 100% convinced that's actually correct.

**Comment by PSteinhaus** [comment]
Merging it would at least make the behaviour of spaces on the right when using right alignment consistent with how spaces on the left side work when text is left aligned, wouldn't it? So I'd say it's an improvement in consistency.

**Comment by alexheretic** [comment]
> Merging it would at least make the behaviour of spaces on the right when using right alignment consistent with how spaces on the left side work when text is left aligned, wouldn't it? So I'd say it's an improvement in consistency.

Yeah yours is the first opinion on this for a while. I'm leaning toward merging this too, I don't think they'll be too many drawbacks or places where people were relying on the current behaviour.

**Comment by alexheretic** [comment]
This is addressed in [_glyph_brush_layout_ `0.2.3`](https://github.com/alexheretic/glyph-brush/releases/tag/glyph-brush-layout-0.2.3).

I imagine they'll be new edge cases to handle, please raise new issues for them :)
