### ISSUE TITLE
how to get glyph width

### ISSUE THREAD

**Issue by crowlKats** [alexheretic/glyph-brush#133]
I am most likely doing something completely wrong, but to get a map of the glyph widths I currently do
```rust
let font_width_map = font
  .codepoint_ids()
  .map(|(glyph, c)| {
    (c, font.glyph_bounds(&glyph.with_scale(scale)).width())
  })
  .collect::<HashMap<char, f32>>();
```
but this seems not to be working properly. is there some other function i should be looking at?

My usecase is that i am trying to make a cursor for text editing, so i need to figure out the width of a glyph to know how much i need to jump by

**Comment by alexheretic** [comment]
Layout glyph width isn't this simple, there's kerning etc. Unless you're using a monospace font in which case it's simpler as all glyphs have the same advance & side-bearing.

_glyph-brush_ doesn't provide anything special for text editing, it's focused on rendering. But running layout with give you the position of each glyph along with the `section_index` & `byte_index` so there should be enough there to position your cursor.

**Comment by crowlKats** [comment]
running layout indeed did what i needed, thank you very much!
