### ISSUE TITLE
DrawCache.rows seems to be uninitialized in some cases leading to panic

### ISSUE THREAD

**Issue by PSteinhaus** [alexheretic/glyph-brush#137]
I've been looking over [this issue in ggez](https://github.com/ggez/ggez/issues/898) and found that I should report it here.

The panic seems to be caused by trying to insert in ```DrawCache.rows``` in ```DrawCache::cache_queued()```, which seems to be unitialized at that point (that point being the first draw in the winit event loop).

Sadly this seems to be hard to reproduce, so I probably can't offer you much help.
The good thing is that it might be relatively easy to fix, right? I've only glanced at the surface of glyph-brush so far, so I have no idea really, but making sure that the LinkedHashMap is initialized sounds doable.

**Comment by alexheretic** [comment]
Hello, this sounds very much like a _linked-hash-map_ bug. Can you check your lockfile to ensure your running the latest version of that crate `0.5.4` as I believe this fixed similar issues.

**Comment by PSteinhaus** [comment]
Oh, that could of course be the case.
We're now running ```0.5.4```, so I'll double check whether the problem is still acute.

**Comment by PSteinhaus** [comment]
It seems that upgrading to `0.5.4` indeed fixes this issue. So thanks for the hint, it seems you were right.

**Comment by alexheretic** [comment]
Thanks for the update, glad the issue is fixed.
