### ISSUE TITLE
Custom elements

### ISSUE THREAD

**Issue by FredrikNoren** [alexheretic/glyph-brush#146]
Hi,

Amazing library first of all!

I have one question though; is it possible to incorporate custom elements into a text flow with this? Say for instance I wanted an inline image or custom element in a Section? (I don't need glyph-brush to render these things for me, just to make space in the text-layout and tell me where they should fit)

**Comment by alexheretic** [comment]
Hello, the default layout logic cannot handle this. It only supports glyphs with metrics from (potentially multiple) fonts positioned in a quad.

A custom [`GlyphPositioner`](https://docs.rs/glyph_brush_layout/latest/glyph_brush_layout/trait.GlyphPositioner.html) could be used to allow such functionality while allowing _glyph_brush_ to continue caching the positions and rendering. However, this wouldn't be trivial to implement.

**Comment by FredrikNoren** [comment]
@alexheretic Alright, thanks!
