### ISSUE TITLE
Rendered text has characters in random order

### ISSUE THREAD

**Issue by zarik5** [alexheretic/glyph-brush#149]
I'm trying to move some text rendering code from Java to Rust. This is what I get with the old code, the expected result:
![message old](https://user-images.githubusercontent.com/10350681/164049741-80619bac-7c10-4bbb-b98f-f481b6ff3fc2.png)

Now I'm trying to rewrite it with glyph_brush, but instead I get a garbled result, the characters get rendered in a random order and it doesn't respect the specified layout:
![message new](https://user-images.githubusercontent.com/10350681/164050176-4f60118d-906d-41f0-a7ab-c3d8b3321129.png)

The code used for generating the bitmap is the following:
```rust
    let message = format!(
        "ALVR v{}\nhostname: {hostname}\n \n{message}",
        *ALVR_VERSION,
    );

    let ubuntu_font =
        FontArc::try_from_slice(include_bytes!("../resources/Ubuntu-Medium.ttf")).unwrap();

    let mut brush = GlyphBrushBuilder::using_font(ubuntu_font).build();

    brush.queue(
        Section::new()
            .add_text(Text::new(&message).with_scale(50_f32))
            .with_bounds((1280_f32, 720_f32))
            .with_layout(
                Layout::default()
                    .h_align(HorizontalAlign::Center)
                    .v_align(VerticalAlign::Center),
            ),
    );

    // todo: handle "TextureTooSmall" error
    brush
        .process_queued(
            |rect, data| unsafe {
                crate::updateLoadingTexuture(
                    rect.min[0],
                    rect.min[1],
                    rect.max[0] - rect.min[0],
                    rect.max[1] - rect.min[1],
                    data.as_ptr(),
                );
            },
            |vertex| (),
        )
        .ok();
```

`updateLoadingTexuture` just queues pixel data for the next rendering cycle. Only one draw command is issued when the text changes, I'm pretty sure the bug is not caused by code external to glyph-brush.

**Comment by zarik5** [comment]
Using the same `OpenSans-Light.ttf` font file from the example will not fix the bug.

**Comment by alexheretic** [comment]
It looks like you are rendering the draw cache texture directly. This is not how _glyph-brush_ is designed to work.

`GlyphBrush::process_queued` can return a `BrushAction::Draw(vertices)`. These are the vertices for each glyph in the layout, each vertex includes draw cache texture coordinates it'll use to render.

You can see this in action in the "draw cache guts" example, `cargo run --example draw_cache_guts` where both the text & the draw-cache are rendered side-by-side.
![](https://user-images.githubusercontent.com/2331607/82690363-f97a9380-9c53-11ea-97bc-6f3397cde00f.png)
In the [opengl example](https://github.com/alexheretic/glyph-brush/blob/master/glyph-brush/examples/opengl.rs) you can see a more realistic example where the draw cache is not directly rendered at all.

However, if you _do_ want create a single image as described for a given text layout _glyph-brush_ is not the right tool. You can use [ab-glyph](https://github.com/alexheretic/ab-glyph/tree/master/glyph) directly, perhaps alongside _glyph-brush-layout_, to render each glyph into a large image. The [ab-glyph image example](https://github.com/alexheretic/ab-glyph/blob/master/dev/examples/image.rs) is along these lines.

This rendering style is not as optimal as what _glyph-brush_ uses and will, of course, not benefit from the caching & optimisations provided by _glyph-brush_.

**Comment by zarik5** [comment]
Thank you for the in-depth explanation! I should have at least run the example...
