### ISSUE TITLE
Text clipping

### ISSUE THREAD

**Issue by Xenfo** [alexheretic/glyph-brush#151]
I'm using `glyph_brush_layout` and was wondering if it's possible to click 1 long word.

Ex in Figma:
![Q2iOm3kQ](https://user-images.githubusercontent.com/46873232/166584825-5b0af770-ccd7-43fa-8a60-63134ab4e2e3.png)

Using this library it would just break and error, and if I shorten it it would not respect bounds. If this is possible could I get some help on how to do it?

**Comment by alexheretic** [comment]
You can configure the line break logic, e.g. use [`BuiltInLineBreaker::AnyCharLineBreaker`](https://docs.rs/glyph_brush_layout/latest/glyph_brush_layout/enum.BuiltInLineBreaker.html#variant.AnyCharLineBreaker) or define your own. I'm not sure if that'll be exactly what you need though, it'll work for a single long word though.

By default (`UnicodeLineBreaker`) words are never cut up in this way.

**Comment by Xenfo** [comment]
Ok, thanks for the help
