### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [alexheretic/glyph-brush#153]
Do you have any started work on background color support ?
It can be great to have in on Text and Section.

Do you have any advice to start to implement it ?

Thanks,
Marc-Antoine

**Comment by alexheretic** [comment]
I think rendering not-text is generally out of scope for this lib, though it should provide the all glyph-info you need to render backgrounds & text selection. For example [GlyphBrush::glyphs](https://docs.rs/glyph_brush/0.7.4/glyph_brush/trait.GlyphCruncher.html#method.glyphs) returns info on the position of each rendered glyph on the screen so could be used to calculate rect coords for a selection / background.

[GlyphBrush::glyph_bounds](https://docs.rs/glyph_brush/0.7.4/glyph_brush/trait.GlyphCruncher.html#method.glyph_bounds) may be enough info on it's own to render a rect background for tooltips etc.

**Comment by alexheretic** [comment]
[GlyphBrush::glyphs](https://docs.rs/glyph_brush/0.7.4/glyph_brush/trait.GlyphCruncher.html#method.glyphs) returns the position of every _glyph_ along with it's section & str-byte indexes & font_id.

So if you wanted to underline str byte-index 4 to 14 you can lookup all the glyph positions related this way (and perhaps use the font to provide vertical metrics).

**Comment by MarcAntoine-Arnaud** [comment]
Thank you for details. I will look to implement that.
