### ISSUE TITLE
glyph_brush_draw_cache: are duplicate queued glyphs eliminated?

### ISSUE THREAD

**Issue by tareksander** [alexheretic/glyph-brush#171]

**Comment by alexheretic** [comment]
When you call `cache_queued` all similar enough queued glyphs will indeed use a single drawn quad in the texture cache. That is the job of the crate.

Note that "duplicate" glyphs may end up drawn into the cache multiple times if queued with different subpixel positions.

Run the [example](https://github.com/alexheretic/glyph-brush/tree/main/draw-cache#example) to see how it works typing different position and size characters.

**Comment by tareksander** [comment]
So I can just queue all glyphs I want to draw and e.g. multiple 'C's with the same parameters get deduplicated? That's great.
