### ISSUE TITLE
Font Fallbacks For Unsupported Characters

### ISSUE THREAD

**Issue by zedseven** [alexheretic/glyph-brush#172]
Hi, does `glyph-brush` support fallback fonts? If the default font doesn't support a certain character, can I make `glyph-brush` fallback to the next font in the list to try to render it?

I haven't found anything about it in the documentation, but I may have missed something.

Currently, unrecognised characters are rendered as question marks, even if I provide a backup font in the `GlyphBrushBuilder`. I know the backup font supports the characters because if I switch the order that I provide them to `GlyphBrushBuilder::using_fonts`, the characters are rendered without an issue.

Thank you!

**Comment by alexheretic** [comment]
There isn't support out of the box for that currently in _glyph-brush_. You have to explicitly declare which font to use for each section.

**Comment by zedseven** [comment]
Alright, thank you for your quick response!
