### ISSUE TITLE
Text Decorations

### ISSUE THREAD

**Issue by indietyp** [alexheretic/glyph-brush#173]
I am currently trying to implement tex decorations (such as strikethrough and underline) on top of `glyph_brush`.

My current predicament is that I am unable to figure out which glyph I am currently drawing (I am only able to know the position and texture index etc.). This makes it quite hard to determine where to correctly place the text decoration based on the line (which I determined beforehand via the `y' position of the SectionedGlyph).

Right now, what I am doing - which seems to be working - is getting all the different glyphs, then filtering out any whitespace characters (as the `Glyphpositioner` strips them) (which is why I created https://github.com/alexheretic/ab-glyph/issues/96 first) and then associate the `SectionedGlyph` with the `Glyph` from processing.

**Comment by indietyp** [comment]
This gets especially tricky, because `SectionGlyph` does not expose `Extra`, while the processed glyph does, meaning to get a full picture I need to combine them sooner or later.

**Comment by alexheretic** [comment]
If you want to know whether to strikethrough when generating the glyph vertex, why not include `strikethrough: bool` in your `Extra` type? The `extra` is provided to the vertex generation fn provided to `process_queued` to handle anything you need to generate vertex info.

You can split up your text into multiple `Section::text`s depending on which parts are strikethrough, in the same why you would for color.

**Comment by alexheretic** [comment]
Or you can render the strikethrough on top of the line as an additional draw. Maybe that's more realistic (I haven't implemented strikethrough so I'm not 100% up to speed).

You can get the `SectionGlyph` positions, each has a `section_index` which you can use to lookup from the `Section::text` provided (and in constant time) everything about the glyph, `char`, `scale`, `extra` etc.

**Comment by indietyp** [comment]
I have it so that `Extra` records `strikethrough: bool, underline: bool`.

The problem is only that I need to figure out which character has those extra properties. Ideally, `SectionGlyph` would include a reference to `extra`; that way, I wouldn't need to match the rendered glyph to the `SectionGlyph` [^1][^2]

I currently have a single `Section` with multiple `Text` elements, and there is currently no way to index into a `Section` with a `SectionGlyph` to obtain the `Extra` attribute.

[^1]: although I still think this would be quite a valuable addition.
[^2]: another observation is also, although it doesn't concern my implementation, that the `pixel_coordinates` and `glyph.position` are slightly different (fractional vs. rounded)

**Comment by indietyp** [comment]
for reference I have something like this:

```rust
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub(crate) struct DecorationStyle {
    strikethrough: bool,
    underline: bool,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) struct Glyph {
    pub(crate) bounds: Rect,

    pub(crate) texture_coordinates: Rect,
    pub(crate) pixel_coordinates: Rect,

    pub(crate) decoration: DecorationStyle,
}

impl From<GlyphVertex<'_, DecorationStyle>> for Glyph {
    fn from(vertex: GlyphVertex<DecorationStyle>) -> Self {
        Self {
            bounds: vertex.bounds,

            texture_coordinates: vertex.tex_coords,
            pixel_coordinates: vertex.pixel_coords,

            decoration: *vertex.extra,
        }
    }
}


impl<'canvas> DrawText<'canvas> {
    fn underline_glyph(&mut self, stats: &GlyphStatistics) {
        let mut path = PathBuilder::new();

        // is the `h_side_bearing` correct here? I'm not sure but :shrug:
        path.rect(
            stats.glyph.position.x - stats.font.h_side_bearing(stats.glyph.id),
            stats.glyph.position.y + (stats.glyph.scale.y * 0.075),
            stats.font.h_advance(stats.glyph.id)
                + (stats.font.h_side_bearing(stats.glyph.id) * 2.0),
            2.0,
        );

        let path = path.finish();
        self.canvas.fill(&path);
    }

    fn process(
        &mut self,
        mut brush: GlyphBrush<Glyph, DecorationStyle, FontArc>,
        fonts: &[FontArc],
        section: Section<DecorationStyle>,
    ) {
		// [...]
        for (index, glyph) in glyphs.into_iter().enumerate() {
            let statistics = &glyph_stats[index];

            let buffer = texture.pixel_buffer(glyph.texture_coordinates);
            let pixel_coordinates = glyph.pixel_coordinates;
            let offset = Point::new(pixel_coordinates.min.x, pixel_coordinates.min.y);

            buffer.commit(offset, &mut self.canvas.target);

            let decoration = glyph.decoration;
            if decoration.has_underline() {
                self.underline_glyph(statistics);
            }

            if decoration.has_strikethrough() {
                self.strikethrough_glyph(statistics);
            }
        }
	}
}
```

**Comment by alexheretic** [comment]
I haven't read everything you posted yet, but I can answer this point, at least, now which may help:

> I currently have a single Section with multiple Text elements, and there is currently no way to index into a Section with a SectionGlyph to obtain the Extra attribute.

I think there is _exactly_ that. It is called `section_index`. It is the index of the text in the `Section::text` vec, the `byte_index` is the index of the char in that text `&str`.

Example
```rust
let section = Section::default()
    .add_text(
        Text::new("hello ")
            .with_scale(12.0)
            .with_color([0.3, 0.3, 0.9, 1.0]),
    )
    .add_text(
        Text::new("world")
            .with_scale(16.0)
            .with_color([0.9, 0.3, 0.3, 1.0]),
    );

for g in glyph_brush.glyphs(&section) {
    let txt = section.text[g.section_index];
    let char = txt.text[g.byte_index..].chars().next().unwrap();
    eprintln!("'{char}' {:?} color={:?}", g.glyph.id, txt.extra.color);
}
```
This prints:
```
'h' GlyphId(75) color=[0.3, 0.3, 0.9, 1.0]
'e' GlyphId(72) color=[0.3, 0.3, 0.9, 1.0]
'l' GlyphId(79) color=[0.3, 0.3, 0.9, 1.0]
'l' GlyphId(79) color=[0.3, 0.3, 0.9, 1.0]
'o' GlyphId(82) color=[0.3, 0.3, 0.9, 1.0]
' ' GlyphId(3) color=[0.3, 0.3, 0.9, 1.0]
'w' GlyphId(90) color=[0.9, 0.3, 0.3, 1.0]
'o' GlyphId(82) color=[0.9, 0.3, 0.3, 1.0]
'r' GlyphId(85) color=[0.9, 0.3, 0.3, 1.0]
'l' GlyphId(79) color=[0.9, 0.3, 0.3, 1.0]
'd' GlyphId(71) color=[0.9, 0.3, 0.3, 1.0]
```

**Comment by indietyp** [comment]
Thank you, this helped tremendously. I was unaware of how to properly use both the indices (I thought that `section_index` might refer to which section has been used, and `byte_index` would be a offset in all section combined). This solved my issue in quite an elegant way.
