### ISSUE TITLE
Question: using draw_queued_with_transform for text in 3d space?

### ISSUE THREAD

**Issue by ucarion** [alexheretic/glyph-brush#19]
Sorry for the noob question, but I'm wondering if what I'm trying to do with this crate makes sense.

I'm trying to draw labels on some objects in 3d-space. I have points in 3d-space where I want to draw text, and I can map them to your typical {-1, 1}^3 cube via an MVP matrix.

I would have thought that I could just map that cube into screen coordinates via something like:

```rust
// Prior to here, I queue sections with "screen position" as their 3d-space x and y coordinates,
// and "z" as their 3d-space z coordinate.

let (width, height, ..) = target.get_dimensions();
let (width, height) = (width as f32, height as f32);
let transform = Matrix4::from_nonuniform_scale(width / 2.0, height / 2.0, 1.0)
    * Matrix4::from_translation([1.0, 1.0, 0.0].into())
    * Matrix4::from_nonuniform_scale(1.0, -1.0, 1.0) * mvp;

self.glyph_brush
    .draw_queued_with_transform(transform.into(), encoder, &target, &stencil)
    .unwrap();
```

But that doesn't seem to work at all -- no text appears on-screen. My assumption here is that `transform * vec4(screen_position, z, 1.0)` needs to map to a rectangle with x-coordinates between 0 and width, and y-coordinates between 0 and height, but I think that assumption is wrong.

I can get all of this to work just fine if I do this 3d->2d conversion "by hand", rather than via the transformation, via something like:

```rust
let screen_position = mvp * Vector4::from(position_in_3d_world_space)

let (width, height, ..) = target.get_dimensions();
let (width, height) = (width as f32, height as f32);
let screen_position_x =
    (width / 2.0) * (1.0 + screen_position.x / screen_position.w);
let screen_position_y =
    (height / 2.0) * (1.0 - screen_position.y / screen_position.w);

self.glyph_brush.queue(gfx_glyph::Section {
    text: label_style.text,
    scale: gfx_glyph::Scale::uniform(label_style.scale),
    screen_position: (screen_position_x, screen_position_y),
    color: label_style.text_color,
    ..gfx_glyph::Section::default()
});

// I then draw this using `draw_queued` -- i.e., with the identity matrix as the transform
```

But this isn't ideal, since it seems to bust the cache whenever `mvp` changes.

Is what I'm trying to do here achievable / a sane thing to do? In any case, I hope my question makes sense. Thanks so much for your time in making this crate, and any help here would be magnanimous and super helpful.

**Comment by ucarion** [comment]
Thinking more about this, one solution (in case the approach of putting world-space values in the screen_position/z fields of `Section` is wrong-headed) would be to always put my labels in the [0,0]x[width,height] rectangle as seems to be expected.

But then the question becomes how to use the view-projection matrix to properly get the right projection to pass to `draw_queued_with_projection`...

**Comment by alexheretic** [comment]
I'm away from my pc for most of today so my help will be a little limited.

Transform use is a little mysterious, it doesn't really tie in with the rest of the API so needs better documentation I think.

One difference is it's the translation is applied on the GPU to gl x,y coords. Ie [-1,1]. So bear that in mind when writing the transform.

**Comment by ucarion** [comment]
I've ended up not using the transform matrix, for now. I don't think I can avoid the fact that text, when transformed to take up a large part of the screen, gets all pixelated.

For now, I'm just computing locations on-screen "by hand". I may circle back to this problem later.

**Comment by alexheretic** [comment]
The glyphs are rendered cpu-side according the the sub-pixel position provided by the layout. That's why if you change the sub-pixel position gpu-side it's likely to look wrong.

Because of this transforms are tricky to use well, but they are "free" performance wise. One application is whole pixel position translations, since such a translation preserves sub-pixel position the pre-rendered glyphs render perfectly after transformation. This trick here is to ensure the transform is aligned with a whole pixel. 

I use this technique for cheap scrolling of a large bunch of sections in robo instructus.

But if what you want to do _does_ involve a sub-pixel position change and the performance cpu-side is ok then what you're doing is probably ok.

**Comment by alexheretic** [comment]
Since `0.10.1` we're a lot more tolerant of sub-pixel position changes (like rotation). But the fundamentals are still true, if you're zooming in you probably need to re-render the glyphs.

**Comment by alexheretic** [comment]
Two strategies are viable with the recent releases:
* transform cpu-side for pixel aligned rasterization
* render large at `(0, 0)` and transform on the gpu with texture-filtering (default enabled)

I'll close this issue for now, please raise new ones for specific improvements or ideas.
