### ISSUE TITLE
Rendering artifacts due to issue in Rusttype

### ISSUE THREAD

**Issue by portstrom** [alexheretic/glyph-brush#38]
gfx_glyph currently paints some glyphs at the wrong position or with the wrong size due to an issue in Rusttype.

https://gitlab.redox-os.org/redox-os/rusttype/issues/121

**Comment by alexheretic** [comment]
@portstrom can you provide some example code to reproduce the issue?

**Comment by portstrom** [comment]
@alexheretic Rendering more than a few lines of anything in Roboto-Regular size 20 should suffice. I can provide some code if required.

**Comment by alexheretic** [comment]
roboto-regular scale 20 paragraph example looks ok

![roboto-reg-scale-20-paragraph](https://user-images.githubusercontent.com/2331607/45045146-09120d00-b06a-11e8-95f2-6162f35d58f7.png)

**Comment by alexheretic** [comment]
Sorry that example does multiple scale by dpi factor, still actual 20 also looks ok

![](https://user-images.githubusercontent.com/2331607/45046299-a7ec3880-b06d-11e8-913b-e8f51b5c0783.png)

**Comment by alexheretic** [comment]
Fixed in rusttype 0.7.1
