### ISSUE TITLE
Question: plans for gfx-hal

### ISSUE THREAD

**Issue by icefoxen** [alexheretic/glyph-brush#41]
Just thinking ahead for the future a little; the step after next for ggez is to switch to gfx-hal, since by hearsay it's basically ready for prime time. Are you intending to make that switch, which will probably be a fairly significant change? Is there anything I can do to help you get there, if so?

**Comment by alexheretic** [comment]
Yes I think gfx-glyph should move with gfx. We can start developing this in a branch, I think it should be fairly straightforward as long as the glyph-brush abstractions still work.

**Comment by icefoxen** [comment]
Yeah, hopefully they will. I have I been following closely but it looks like you've been refactoring a lot, and ggez devel hasn't followed it yet. But using gfx-hal is a goal for the next-next version, so I want to know what state my dependencies are in. Again, happy to help where necessary.

**Comment by icefoxen** [comment]
The separation into the `glyph-brush` crate makes this basically not an issue, since ggez can take over the drawing pipeline entirely.  <3

**Comment by alexheretic** [comment]
In case anyone digs this issue up in regards to gfx-glyph gfx-hal support, my current plan is **not** to transition gfx-glyph to this any time soon. Instead glyph-brush provides most of the goodness without a render-api allegiance, and so of course can be used with gfx-hal.

**Comment by icefoxen** [comment]
Seconded; `ggez` now uses glyph-brush and ties it into its own rendering system and it works great.
