### ISSUE TITLE
`glyph_brush` readme example is incorrect

### ISSUE THREAD

**Issue by icefoxen** [alexheretic/glyph-brush#44]
The `glyph_brush` readme says to run `cargo run --example opengl --release` to run the example.  Trying to do this, in the `glyph-brush` subdirectory or in the project toplevel directory (that is, `glyph-brush` or `glyph-brush/glyph-brush`) both result in cargo saying `error: no example target named 'opengl'`.  To make it run correctly, you must do `cargo run -p glyph_brush --example opengl --release`, in either directory.

Thank you!

**Comment by alexheretic** [comment]
I removed `default-members` from the top-level workspace manifest. Should work now!
