### ISSUE TITLE
Obtaining width/height of the text

### ISSUE THREAD

**Issue by est31** [alexheretic/glyph-brush#47]
In order to draw and layout text with non-text elements, I often need to know its width/height.

One example would be a grey area as the background of some text.

Another one is if I want the text to be centered by the x and y coordinates in the middle of the screen.

But even if you just want to render into an image file, you need to know its size.

What I did was the following:

```Rust
fn get_section_bounding_box<'a, 'b>(section :&Section, glyph_brush :&GlyphBrush<'a, 'b>) -> Option<rt::Rect<i32>> {
	let geom = SectionGeometry {
		screen_position : section.screen_position,
		bounds : section.bounds,
	};
	let section_text = SectionText {
		text : section.text,
		scale : section.scale,
		color : section.color,
		font_id : section.font_id,
	};

	// https://github.com/alexheretic/glyph-brush/pull/46
	struct FontHack<'a>(&'a[rt::Font<'a>]);
	impl<'font> FontMap<'font> for FontHack<'font> {
		#[inline]
		fn font(&self, i :FontId) -> &rt::Font<'font> {
			&self.0[i.0]
		}
	}

	let sx = 1.0; //section.scale.x;
	let sy = 1.0; //4.0; //section.scale.y;
	let fonts :&[rt::Font<'_>] = &glyph_brush.fonts();
	let mut boxes = section.layout.calculate_glyphs(&FontHack(fonts), &geom, &[section_text])
		.into_iter()
		.filter_map(|v| {
			let pos = v.0.position();
			v.0.into_unpositioned().exact_bounding_box()
				.map(|b| { rt::Rect {
					min : rt::Point {
						x : (b.min.x * sx + pos.x) as i32,
						y : (b.min.y * sy + pos.y) as i32,
					},
					max : rt::Point {
						x : (b.max.x * sx + pos.x) as i32,
						y : (b.max.y * sy + pos.y) as i32,
					},
				}})
		})
		.collect::<Vec<_>>();
	boxes.push(rt::Rect {
		min : rt::Point {
			x : section.screen_position.0 as i32,
			y : section.screen_position.1 as i32,
		},
		max : rt::Point {
			x : section.screen_position.0 as i32,
			y : section.screen_position.1 as i32,
		}
	});
	let min_x = boxes.iter().map(|v|v.min.x).min()?;
	let min_y = boxes.iter().map(|v|v.min.y).min()?;
	let max_x = boxes.iter().map(|v|v.max.x).max()?;
	let max_y = boxes.iter().map(|v|v.max.y).max()?;
	Some(rt::Rect {
		min : rt::Point {
			x : min_x,
			y : min_y,
		},
		max : rt::Point {
			x : max_x,
			y : max_y,
		},
	})
}
```

Basically using `calculate_glyphs` and maximizing/minimizing the bounding boxes.

But this algorithm doesn't really work, it's off by many measures. Do you know why?

It would be cool to have an "official" way of retrieving the width/height, in the best case without having to render anything (like here).

**Comment by alexheretic** [comment]
Check out [`pixel_bounds`](https://docs.rs/glyph_brush/0.2.2/glyph_brush/trait.GlyphCruncher.html#method.pixel_bounds):

```rust
if let Some(bounds) = glyph_brush.pixel_bounds(section) {
    println!("width: {}", bounds.width());
}
```

**Comment by alexheretic** [comment]
You can/should also use [`glyphs`](https://docs.rs/glyph_brush/0.2.2/glyph_brush/trait.GlyphCruncher.html#method.glyphs) to make get positioned glyphs this caches layouts calls. Generally you shouldn't need to use `glyph_brush_layout`'s functions much if you're using `glyph_brush`.

**Comment by est31** [comment]
Oh cool, thanks, will try it out!

**Comment by est31** [comment]
I can confirm that the `pixel_bounds` function is working. Thanks again!
