### ISSUE TITLE
Rename the `to_vertex` callback to `to_quad` and document it a bit better?

### ISSUE THREAD

**Issue by icefoxen** [alexheretic/glyph-brush#50]
I'm making this partially so that I can understand better... if I have it right, `process_queued()` takes a callback called `to_vertex` that basically contains the all drawing information for a single character.  UV, target position, etc.  In the `opengl.rs` example this gets expanded to a full quad in the vertex shader, as far as I can tell, but I don't want to do that 'cause it involves switching shaders back and forth a lot. I'm still sorta figuring out what all the pieces are and how they're used.

**Comment by alexheretic** [comment]
I've updated the docs
```rust
/// Processes all queued sections, calling texture update logic when necessary &
/// returning a `BrushAction`.
/// See [`queue`](struct.GlyphBrush.html#method.queue).
///
/// Two closures are required:
/// * `update_texture` is called when new glyph texture data has been drawn for update in the
///   actual texture.
///   The arguments are the rect position of the data in the texture & the byte data itself
///   which is a single `u8` alpha value per pixel.
/// * `to_vertex` maps a single glyph's `GlyphVertex` data into a generic vertex type. The
///   mapped vertices are returned in an `Ok(BrushAction::Draw(vertices))` result.
///   It's recommended to use a single vertex per glyph quad for best performance.
///
/// Trims the cache, see [caching behaviour](#caching-behaviour).
```

**Comment by alexheretic** [comment]
@icefoxen are the new docs sufficient do you think? Can we make it clearer still?

**Comment by icefoxen** [comment]
Looks good to me.  :+1:

**Comment by alexheretic** [comment]
Cool! I'll close this then.
