### ISSUE TITLE
Remove dependency on layout features

### ISSUE THREAD

**Issue by portstrom** [alexheretic/glyph-brush#53]
As it is now, the only way to display some text with gfx_glyph is to create a `Section` and let gfx_glyph do the layout and caching. `Section` is a document model that is too restrictive for advanced use cases and too bloated for simple use cases, and is not extensible. It's also very slow. The caching doesn't even work well. Doing something as simple as scrolling causes the section to have a different hash, and then the expensive layout calculation is repeated all over again.

It would be better to remove it from gfx_glyph and let the caller to its own layout and caching and simply feed the positioned glyphs into gfx_glyph. If the caller wants some convenient layout library, one can easily be added on top of this low level interface. When glyph_layout was split out of gfx_glyph, I would have expected glyph_layout to be an optional higher level library, allowing people to create different layout libraries for different use cases, but instead gfx_glyph now depends on glyph_brush, and there's no way to opt out of using it.

I have made a simplified version of gfx_glyph, removing the layout features along with section caching, and letting the caller supply positioned glyphs directly. I have over the last few months got plenty of experience using it in three applications for internal use, including components such as a rich text editor, plain text editor and spreadsheet editor, as well as lots of simple lines of text, and it works remarkably well. When I first tried this change, I didn't have any section caching at all, and it was already faster than the original gfx_glyph with caching enabled. Now I make it even faster simply by caching my sections in an `Option`, calling the method `get_or_insert_with` whenever I need the section. No hashing required. The same cache can be kept when scrolling, and translation applied cheaply.

I have published my simplified version of gfx_glyph together with an example program that displays an HTML document: https://github.com/portstrom/simplified_gfx_glyph
Feedback is appreciated.

**Comment by alexheretic** [comment]
It's certainly true that there are flaws with the layout caching currently, something like colour changes or position changes cause layout to re-run. However these can be optimised, improving caching or avoiding section changes like using a gpu transform to scroll.

Hashing allows draw caching where texture cache interaction, vertex generation & upload are all avoided. I've found the cost of hashing to be insignificant in comparison with the other parts of the process.

But I think there is a use case here that gfx-glyph isn't serving, I don't see why we can't accept pre-positioned glyphs in addition to the dynamically positioned ones. `fn queue_pre_positioned(...)` perhaps.

Are you interested in having this crate provide this functionality?

**Comment by portstrom** [comment]
I'm interested in having this crate accept positioned glyphs, but I don't see a reason to have it in addition to dynamically positioned ones. I think doing layout can be handled by a different crate, which passes positioned glyphs into this crate. The cost of every other part of the process is insignificant in comparison to positioning glyphs.

**Comment by alexheretic** [comment]
I can't avoid texture cache & vertex generation with that architecture. This optimisation perhaps doesn't matter to you, but does to me as it enables peak performance of unchanging text. I would implore you to at least imagine that a different point of view can exist here.

I can add the methods to accept pre-positioned glyphs, which satisfies your use case and doesn't affect the current use case. This seems like a win win.

In any case, I'll add the methods and you can, of course, use them or not. I accept that the lib is less interesting to people that aren't interested in dynamic caching layouts, because this is what the lib is about. Rolling your own rusttype renderer with different goals is fine, good luck with your crate.

**Comment by portstrom** [comment]
I see no reason making the layout features optional would prevent caching the generated vertex buffer.

**Comment by portstrom** [comment]
I updated my repository to add a public method to draw from cache: https://github.com/portstrom/simplified_gfx_glyph/commit/165575f600a374711100b2f298692636504e9e3e
You could make a higher level layout crate that wraps around this low level interface and does layout and hashing, delegating rendering to this low level interface using either the `draw_cached` method when hashes match, or the `draw_queued` method otherwise. That way, the layout crate can provide the same interface as gfx_glyph currently provides, and those who need something different can replace the layout crate with one that has different capabilities, or use the low level interface directly, still using the same low level crate and not linking any of the unused layout code into the program.

**Comment by alexheretic** [comment]
The new fn is available in gfx-glyph `0.13.2`.
