### ISSUE TITLE
Strange caching behavior on 2-tuples with both entries being single digit

### ISSUE THREAD

**Issue by chinedufn** [alexheretic/glyph-brush#58]
Alright so I'm getting some weird behavior in an application that I'm working on.

If nothing comes to mind I can try to pair down a simpler example... But I'd like to start with an illustration in case anything obvious comes to mind.

## Problem

I migrated from `rusttype` to `glyph_brush` which I know uses rusttype under the hood today.

Everything has gone smooth except for some weird caching behavior.

---

I'm rendering a string that looks like this

`Hovered Tile: Some((0, 0))`

Where the coordinates might be anything up to `64x64`

When I first mouse over any tile the text will get rendered properly.

Anytime I mouse over a tile where at least one of the elements is double digits (10+, 10+) - things work fine.

What doesn't work is if I mouse over a tile that is single digit and then mouse over another single digit tile that I've already moused over. The old text gets redrawn.

Does anything about rendering the debug string for `Option<(u16, u16)>` seem like it might trigger this kind of behavior...?

---

Again - if this description isn't very useful I can think about a more paired down example or maybe provide more details / answer questions... But mainly wondering if anything rings a bell here.

**Comment by chinedufn** [comment]
Alright so from looking at the code it looks like one thing that triggers `Redraw` is the comparison of the new and old `text_state`

So looking here..:

https://github.com/alexheretic/glyph-brush/blob/2ba95fc8dcb1988bba236a8520547d2046a601b7/glyph-brush/src/glyph_brush.rs#L282-L288

I wonder if there might for whatever reason be the same hash for different text.

I'll give this a look ...

**Comment by alexheretic** [comment]
Hi can you log the queue & process calls so I can try to reproduce this in example code?

**Comment by alexheretic** [comment]
I released new optimisations today around changing text, so they could be to blame. You can try `0.3.0` to see if that's the case.

Either way I'd be interested in getting to the bottom of the issue.

**Comment by chinedufn** [comment]
Sure can!

I quite literally started using this today so I'm on `0.3.0`

So here's what I'm passing into `brush.queue`

```
Section {
    text: "Hovered Tile: Some((0, 0))",
    screen_position: (
        5.0,
        60.0
    ),
    bounds: (
        inf,
        inf
    ),
    scale: Scale {
        x: 20.0,
        y: 20.0
    },
    color: [
        1.0,
        1.0,
        1.0,
        1.0
    ],
    z: 0.0,
    layout: Wrap {
        line_breaker: UnicodeLineBreaker,
        h_align: Left,
        v_align: Top
    },
    font_id: FontId(
        0
    )
}
Section {
    text: "Hovered Tile: Some((1, 0))",
    screen_position: (
        5.0,
        60.0
    ),
    bounds: (
        inf,
        inf
    ),
    scale: Scale {
        x: 20.0,
        y: 20.0
    },
    color: [
        1.0,
        1.0,
        1.0,
        1.0
    ],
    z: 0.0,
    layout: Wrap {
        line_breaker: UnicodeLineBreaker,
        h_align: Left,
        v_align: Top
    },
    font_id: FontId(
        0
    )
}
8web_client.js:825 Section {
    text: "Hovered Tile: Some((0, 0))",
    screen_position: (
        5.0,
        60.0
    ),
    bounds: (
        inf,
        inf
    ),
    scale: Scale {
        x: 20.0,
        y: 20.0
    },
    color: [
        1.0,
        1.0,
        1.0,
        1.0
    ],
    z: 0.0,
    layout: Wrap {
        line_breaker: UnicodeLineBreaker,
        h_align: Left,
        v_align: Top
    },
    font_id: FontId(
        0
    )
}
```

So with those three here's what happens (again - sorry I'm stripping this all out of a much larger application so I can continue to pare down as needed!)

So with the three sections that I printed out about:

1. Pass in first section. Then process queue `BrushAction::Draw`. All good here

2. Pass in second section. Then process queue. `BrushAction::Draw`. Renders fine

3. Pass in third section. Then process queue. `BrushAction::ReDraw` Now I have the wrong text

**Comment by chinedufn** [comment]
Oh hmm I see there is a `0.4.0`. I'll try that right now.

**Comment by alexheretic** [comment]
Thanks that's helpful. I will try to reproduce in the morning.

In the mean time you can disable draw caching see https://docs.rs/glyph_brush/0.3.0/glyph_brush/struct.GlyphBrushBuilder.html#method.cache_glyph_drawing

**Comment by chinedufn** [comment]
Sounds great - just migrated to `0.4.0` and seeing the same issue. In the meantime I'll disable caching. Thanks!

**Comment by chinedufn** [comment]
Alright heading to bed but one other thing

`cache_glyph_drawing` did not fix the problem

However, `cache_glyph_positioning` does fix it. 

```
// This works for me
let mut brush = GlyphBrushBuilder::using_font_bytes(font)
.cache_glyph_positioning(false)
.build();
```

**Comment by alexheretic** [comment]
Here's how I tried to reproduce it; I rigged the opengl example to render your section A then B every second.

<details><summary>patch</summary>
<p>

```patch
diff --git a/glyph-brush/examples/opengl.rs b/glyph-brush/examples/opengl.rs
index dbaa0f4..5e05c62 100644
--- a/glyph-brush/examples/opengl.rs
+++ b/glyph-brush/examples/opengl.rs
@@ -157,6 +157,22 @@ fn main() -> Res<()> {
         .ok_or("get_inner_size = None")?
         .to_physical(window.get_hidpi_factor());
 
+    let start = std::time::Instant::now();
+    let section_a = Section {
+        text: "Hovered Tile: Some((0, 0))",
+        screen_position: (5.0, 60.0),
+        scale: Scale { x: 20.0, y: 20.0 },
+        color: [1.0, 1.0, 1.0, 1.0],
+        ..<_>::default()
+    };
+    let section_b = Section {
+        text: "Hovered Tile: Some((1, 0))",
+        screen_position: (5.0, 60.0),
+        scale: Scale { x: 20.0, y: 20.0 },
+        color: [1.0, 1.0, 1.0, 1.0],
+        ..<_>::default()
+    };
+
     while running {
         loop_helper.loop_start();
 
@@ -220,41 +236,37 @@ fn main() -> Res<()> {
         });
 
         let width = dimensions.width as f32;
-        let height = dimensions.height as _;
-        let scale = Scale::uniform((font_size * window.get_hidpi_factor() as f32).round());
-
-        glyph_brush.queue(Section {
-            text: &text,
-            scale,
-            screen_position: (0.0, 0.0),
-            bounds: (width / 3.15, height),
-            color: [0.9, 0.3, 0.3, 1.0],
-            ..Section::default()
-        });
-
-        glyph_brush.queue(Section {
-            text: &text,
-            scale,
-            screen_position: (width / 2.0, height / 2.0),
-            bounds: (width / 3.15, height),
-            color: [0.3, 0.9, 0.3, 1.0],
-            layout: Layout::default()
-                .h_align(HorizontalAlign::Center)
-                .v_align(VerticalAlign::Center),
-            ..Section::default()
-        });
-
-        glyph_brush.queue(Section {
-            text: &text,
-            scale,
-            screen_position: (width, height),
-            bounds: (width / 3.15, height),
-            color: [0.3, 0.3, 0.9, 1.0],
-            layout: Layout::default()
-                .h_align(HorizontalAlign::Right)
-                .v_align(VerticalAlign::Bottom),
-            ..Section::default()
-        });
+        let height = dimensions.height as f32;
+        // let scale = Scale::uniform((font_size * window.get_hidpi_factor() as f32).round());
+
+        let draw_a = start.elapsed().as_secs() % 2 == 0;
+
+
+        glyph_brush.queue(if draw_a { section_a } else { section_b });
+
+        // glyph_brush.queue(Section {
+        //     text: &text,
+        //     scale,
+        //     screen_position: (width / 2.0, height / 2.0),
+        //     bounds: (width / 3.15, height),
+        //     color: [0.3, 0.9, 0.3, 1.0],
+        //     layout: Layout::default()
+        //         .h_align(HorizontalAlign::Center)
+        //         .v_align(VerticalAlign::Center),
+        //     ..Section::default()
+        // });
+        //
+        // glyph_brush.queue(Section {
+        //     text: &text,
+        //     scale,
+        //     screen_position: (width, height),
+        //     bounds: (width / 3.15, height),
+        //     color: [0.3, 0.3, 0.9, 1.0],
+        //     layout: Layout::default()
+        //         .h_align(HorizontalAlign::Right)
+        //         .v_align(VerticalAlign::Bottom),
+        //     ..Section::default()
+        // });
 
         let mut brush_action;
         loop {
@@ -303,6 +315,7 @@ fn main() -> Res<()> {
         }
         match brush_action? {
             BrushAction::Draw(vertices) => {
+                dbg!("Drawing");
                 // Draw new vertices
                 vertex_count = vertices.len();
                 unsafe {

```

</p>
</details>

However, I couldn't reproduce an issue. `BrushAction::Draw`s are correctly returned each second.

Can you reproduce the issue with the opengl example? Or maybe we should make a wasm example.

**Comment by alexheretic** [comment]
My feeling is this must be some hash collisions that occurs in wasm32. Can you try a different hasher, like [xx](https://github.com/shepmaster/twox-hash) or default sip to test this idea?

**Comment by alexheretic** [comment]
Ok I can confirm this is definitely caused by seahash collision at 32bit, and glyph_brush's own reliance on collision free hashing to avoid string cloning / lifetime issues.

I will eventually end my reliance on collision free hashing, but I'm surprised with seahash in 32bit. I'll will switch back to xxHash as default as it stays collision free in this simple test. I'll add 32bit testing targets too.

**Comment by chinedufn** [comment]
> Ok I can confirm this is definitely caused by seahash collision at 32bit

Awesome! How did you end up figuring this out?

> I will eventually end my reliance on collision free hashing

Just curious - what will you do instead?

—-

Thanks for finding the problem!!

**Comment by alexheretic** [comment]
> Awesome! How did you end up figuring this out?

I wrote a test for the default hasher that seahash seems to fail in any 32-bit environment _(I ran it in i686-unknown-linux-musl)_.

```rust
#[test]
fn default_section_hasher() {
    use std::hash::{BuildHasher, Hash, Hasher};

    let section_a = Section {
        text: "Hovered Tile: Some((0, 0))",
        screen_position: (5.0, 60.0),
        scale: Scale { x: 20.0, y: 20.0 },
        color: [1.0, 1.0, 1.0, 1.0],
        ..<_>::default()
    };
    let section_b = Section {
        text: "Hovered Tile: Some((1, 0))",
        screen_position: (5.0, 60.0),
        scale: Scale { x: 20.0, y: 20.0 },
        color: [1.0, 1.0, 1.0, 1.0],
        ..<_>::default()
    };
    let hash = |s: &Section| {
        let s: VariedSection = s.into();
        let mut hasher = DefaultSectionHasher::default().build_hasher();
        s.hash(&mut hasher);
        hasher.finish()
    };
    assert_ne!(hash(&section_a), hash(&section_b));
}
```

> > I will eventually end my reliance on collision free hashing

> Just curious - what will you do instead?

A bit like a hash map I'll own the data for equality testing after hash testing. Right now it's difficult to do this without either always cloning the string data, or requiring `'static` lifetime. Both are undesirable, so I rely on collision free hashing. I'll look into this if I get round to pursuing async multithreaded section layout / vertex gen.

But collision free hashing has worked out very well, at least in 64-bit. I think we just bumped into a seahash edge here.

**Comment by alexheretic** [comment]
Hey the default hasher will switch to xxHash in the next release. Until then I'd recommend using xxHash or std `RandomState` manually until the next version is out.

**Comment by chinedufn** [comment]
Perfect thanks again
