### ISSUE TITLE
Optional depth target on `gfx_glyph` draw methods

### ISSUE THREAD

**Issue by hecrj** [alexheretic/glyph-brush#65]
I noticed some of my 2D render targets do not have a depth buffer :sweat_smile:

Is there any way to use the `gfx_glyph` draw methods without one? Maybe they could take an `Option`?

**Comment by alexheretic** [comment]
You can just pass it the main depth buffer for the render target, the default depth test is `gfx::preset::depth::PASS_TEST` which doesn't actually update it anyway.

I wouldn't be against a way to render without the depth stuff, but I'm not convinced it will be worth the effort. Feel free to have a crack at it!

**Comment by hecrj** [comment]
> You can just pass it the main depth buffer for the render target

I tried tried it, but once I render off-screen on a target with a different size I get a debug assertion panic. Also, it's a bit hacky :sweat_smile: Maybe I didn't understand you well.

In any case, I gave it a shot by doing compiler-driven development. Check #66.
