### ISSUE TITLE
`GlyphBrush::pixel_bounds` seems to return incorrect bounds

### ISSUE THREAD

**Issue by hecrj** [alexheretic/glyph-brush#68]
`GlyphBrush::pixel_bounds` seems to return an incorrect result. I found about this when working on [basic GUI support for Coffee](https://github.com/hecrj/coffee/pull/35). You can find more details in https://github.com/hecrj/coffee/issues/43.

Here is an SSCCE using `gfx_glyph` ([full code](https://gist.github.com/hecrj/b7468d4e46e820c1ba990445d149e966)):

```rust
let section = Section {
    text: "Pixel bounds test",
    screen_position: (50.0, 50.0),
    scale: Scale::uniform(30.0),
    color: [1.0, 1.0, 1.0, 1.0],
    ..Section::default()
};

let bounds = glyph_brush.pixel_bounds(section).unwrap();

glyph_brush.queue(Section {
    bounds: (bounds.width() as f32, bounds.height() as f32),
    ..section
});
```

Which produces:

![image](https://user-images.githubusercontent.com/518289/59431680-bc701500-8de5-11e9-9d90-537c6a8e2008.png)

Is this a bug, or am I wrong when I assume the returned `pixel_bounds` should be compatible with `Section::bounds`? I will investigate a bit and try to find the issue.

**Comment by alexheretic** [comment]
`pixel_bounds` are indeed not compatible with layout bounds.

`pixel_bounds` describes the minimum box that can hold the rendered result.
> The box is a conservative whole number pixel rectangle that can contain the section.

`screen_position` & `bounds` however relate to the layout, none of the built-in layouts have an origin that will make the top-left pixel _(I guess unless the first glyph is a square matching the ascent)_.

This is why it has the 'pixel_' prefix, and relates closely to rusttype's `pixel_bounding_box`

**Comment by alexheretic** [comment]
It might be cool to have something like a `layout_bounds` method, that would return a box in terms of glyph advance-width * descent from the baseline. You'd be able to use this for drawing box backgrounds around dynamic text.

Right now you can access this info using the `glyphs` iterator.

**Comment by alexheretic** [comment]
`layout_bounds` would be useful actually, not that I've been misusing pixel_bounds myself as a lazy way to calculate tooltip backgrounds, who said that?!

I'm testing out this for layout-bound calculation:
```rust
use glyph_brush::{rusttype::*, *};
use std::borrow::Cow;

pub trait ExtGlyphCruncher {
    fn layout_bounds<'a, S>(&mut self, section: S) -> Option<Rect<f32>>
    where
        S: Into<Cow<'a, VariedSection<'a>>>;
}

impl<'font, T> ExtGlyphCruncher for T
where
    T: GlyphCruncher<'font>,
{
    #[inline]
    fn layout_bounds<'a, S>(&mut self, section: S) -> Option<Rect<f32>>
    where
        S: Into<Cow<'a, VariedSection<'a>>>,
    {
        self.glyphs(section).fold(None, |b, glyph| {
            if let Some(font) = glyph.font() {
                let hm = glyph.unpositioned().h_metrics();
                let vm = font.v_metrics(glyph.scale());
                let pos = glyph.position();
                let lbound = Rect {
                    min: point(pos.x - hm.left_side_bearing, pos.y - vm.ascent),
                    max: point(pos.x + hm.advance_width, pos.y - vm.descent),
                };

                b.map(|b| {
                    let min_x = b.min.x.min(lbound.min.x);
                    let max_x = b.max.x.max(lbound.max.x);
                    let min_y = b.min.y.min(lbound.min.y);
                    let max_y = b.max.y.max(lbound.max.y);
                    Rect { min: point(min_x, min_y), max: point(max_x, max_y) }
                })
                .or_else(|| Some(lbound))
            } else {
                b
            }
        })
    }
}
```

**Comment by hecrj** [comment]
> pixel_bounds are indeed not compatible with layout bounds.

I see! My bad.

> It might be cool to have something like a layout_bounds method, that would return a box in terms of glyph advance-width & descent from the baseline.

Right, I need this to measure text nodes when computing UI layout. I will give it a shot! It looks like we will need to use `PositionedGlyph::font` and `PositionedGlyph::id`, then use `Font::glyph`, and then finally `Glyph::get_data`? Is there an easier way to obtain the advance-width... _Sees new comment_

Oh, you just commented! :sweat_smile: :tada: I don't know much about `rusttype` and font layouting, but it looks reasonable to me.

**Comment by alexheretic** [comment]
Yeah I think it should work ok. Should work with any layout as it's glyph based. I'll have to add some benches to see how well it performs. It also needs decent docs, as the distinction could be confusing.

I'll add this method when I get a chance, probably later on today.

**Comment by hecrj** [comment]
> I'll add this method when I get a chance, probably later on today.

No hurries! And thank you! :)

**Comment by alexheretic** [comment]
Ok I've added this with 7c0eb238a77c02964e729a5049696e1082d3cfe7. I ended up calling it `glyph_bounds`, as the layout bounds is already the name of the specified section bounds (ie the maximum bounds of a section).

**Comment by hecrj** [comment]
Amazing! Thank you again for your insanely quick support!

**Comment by alexheretic** [comment]
No worries, I was kind of "in the area" anyway, just avoiding the issue. I'll make a new release tomorrow.

**Comment by hecrj** [comment]
I just wanted to say that I've implemented the fix on my end and it's working like a charm. Thank you!
