### ISSUE TITLE
0.5.1 breaks semver

### ISSUE THREAD

**Issue by francesca64** [alexheretic/glyph-brush#69]
#67 introduced a breaking API change, but was released with only a patch version bump.

This causes breakage for anyone manually constructing `GlyphBrushBuilder`, since they'll be missing the `gpu_cache_align_4x4` field.

**Comment by alexheretic** [comment]
Thanks, I'll yank it tomorrow.

Tbf manual construction is not the intended usage, for this reason. I'll probably add a private dummy field to ensure this in future. 

Is there a good reason to want to avoid the builder methods for construction?

**Comment by francesca64** [comment]
> Is there a good reason to want to avoid the builder methods for construction?

Not that I know of; I prefer them too.

**Comment by alexheretic** [comment]
Ok as I judge this a public api bug I've yanked _0.5_ & _0.5.1_ and released 0.5.2 with `GlyphBrushBuilder` direct construction prevented.
