### ISSUE TITLE
Mismatched types. Two different versions of crate 'rusttype' are being used

### ISSUE THREAD

**Issue by AKholetsky** [alexheretic/glyph-brush#74]
When I build the master branch of ggez the error 'mismatched types' 
is thrown during compilation of glyph_brush v0.6.0. 

Cargo.lock has such dependencies:
[[package]]
name = "glyph_brush"
version = "0.5.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "glyph_brush 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "glyph_brush"
version = "0.6.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "glyph_brush_layout 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.4.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "ordered-float 1.0.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "rustc-hash 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "rusttype 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "twox-hash 1.5.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "glyph_brush_layout"
version = "0.1.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "rusttype 0.7.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "xi-unicode 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
]

**Comment by alexheretic** [comment]
Run `cargo update` 

I went to the effort of making rusttype & glyph-brush types compatible across breaking versions using the semver trick, but this won't work if you don't ever update your lock **at all**.

So for example rusttype `0.7.9` is a non-breaking update for the `0.7.x` versions and is compatible with `0.8.x`. But previous versions won't have that.

**Comment by alexheretic** [comment]
If I understand correctly a `cargo update` fixes any issues from partial updating here. 

Yes thinking about it now, glyph_brush should have depended on the latest glyph_brush_layout patch. But even if I get to yanking and releasing, `cargo update` still needs to be run to actually pull in those changes. So why not just run it now?

**Comment by kvark** [comment]
To clearly indicate on crates.io that this version is broken, avoid future issues by users.

**Comment by alexheretic** [comment]
Sure, I mean I'll do as you suggest when I get a chance. I'm just trying to better understand the scenarios where it can cause issue.

**Comment by kvark** [comment]
I'll make a guess:
  1. user starts by using `glyph_brush-0.5.3`, which depends on `glyph_brush_layout-0.1.5`, both of which depend on `rusttype-0.7`. This information is stored in their `Cargo.lock`.
  2. user updates to `glyph-brush-0.5.4`, which depends on `rusttype-0.8` as well as `glyph_brush_layout-0.1.5`, which still depends on `rusttype-0.7`. Nothing compiles.

**Comment by alexheretic** [comment]
> 2. user updates to glyph-brush-0.5.4, which depends on rusttype-0.8 as well as glyph_brush_layout-0.1.5, which still depends on rusttype-0.7. Nothing compiles.

This is the bit that makes less sense, there doesn't seem to be a reason to make this partial update. Later versions of `glyph_brush_layout` were available at the time. So even after making a partial update it's trivial to fix with `cargo update`. Basically I can't see how this could ever really block development.

But in any case I've published `0.6.1` & yanked `0.6.0`.

**Comment by kvark** [comment]
> there doesn't seem to be a reason to make this partial update

That's a controversial statement. It's perfectly legal and often used to minimize the risk. One could think of a workflow that doesn't even involve a `cargo update` in particular: say, the user adds another dependency that transitively requires `glyph_brush-0.5.4`, and we get in the same situation.

> But in any case I've published 0.6.1 & yanked 0.6.0.

Are you sure that's solving the problem? It depends on whether `rusttype` is a public external dependency. If it is, then, if I understand correctly, `glyph_brush-0.5.3` is not compatible with `glyph_brush-0.5.4`, since they depend on non-compatible `rusttype` versions.

**Comment by alexheretic** [comment]
`rusttype-0.7.9` is compatible with `rusttype-0.8.x` which essentially allows updating to it without a breaking version change. I do think these semver trick updates are beneficial in reducing churn.

**Comment by kvark** [comment]
I do agree that semver trick is very useful! I just think that in this case something went wrong, perhaps the rusttype dependency wasn't bumped on some things, and in the end your trick was implemented incorrectly and broke semver.
