### ISSUE TITLE
Is it possible to find the width of a space character?

### ISSUE THREAD

**Issue by icefoxen** [alexheretic/glyph-brush#75]
Basically, the positioning functions tend to ignore trailing spaces or strings containing only spaces.  See https://github.com/ggez/ggez/issues/687 In fact I can't find a way to get the size of a space character directly at all.

What is the best way to do this?  It's a sort of weird edge case, starting to get more into font layout in general than `glyph_brush`'s caching in particular.  BUT, being able to just say "a space is X units wide" is also really useful for doing quick-and-dirty layout that still works half-decently when text is resized or fonts are changed.  So we're getting into areas where my knowledge of how a font API *should* work is not great.

**Comment by alexheretic** [comment]
The layout width of a glyph is provided by rusttype `HMetrics`.

```rust
font.glyph(' ').scaled(scale).h_metrics()
```
