### ISSUE TITLE
Crisper text

### ISSUE THREAD

**Issue by SetLinux** [alexheretic/glyph-brush#77]
I managed to get an example project up and working easily successfully (thanks for the effort put into this) but I need more crisp text one way is to just render the texture double the size for exampl and then downscale is this possible in glyphbrush? And if not any other way to make the text crisper

**Comment by GreatIndieDeveloper** [comment]
any help on such issue would be v appreciated

**Comment by alexheretic** [comment]
Using larger textures for screen text won't make them higher quality. The best quality text rusttype can do is drawing them exactly as cached as they are rasterized with the exact sub-pixel position they'll be rendered at.

However, if you aim to distort the text, like move it into a non-screen projection, it may make sense to rasterize at a larger size. Glyph-brush/rusttype isn't really designed for this, but you can perhaps feed it doubled screen positions and then convert in the shader or vertex transform.
