### ISSUE TITLE
Allow glyph brush to be created without a font

### ISSUE THREAD

**Issue by chinedufn** [alexheretic/glyph-brush#82]
## Problem

Right now in order to create a glyph brush you need to use the `GlyphBrushBuilder` and add at least one font.

If your application loads fonts during runtime then you cannot create your brush until your font loads.

This means that you need to use a trick such as having `brush: RefCell<Option<GlyphBrush<...>>>` and replacing the `None` with `Some(brush)` whenever your first font loads

## Potential Solution

Perhaps there could be a `GlyphBrushBuilder::new()` method that had all of the same default settings as `add_font_bytes` and the like? In fact the `add_font_bytes` etc could just wrap the `new()` method.

**Comment by alexheretic** [comment]
This was deliberate to ensure that font `0` always existed, so `Section::default()` will always make sense. Otherwise it's possible for a default text section to cause glyph_brush to panic.

One workaround is just to load one static font into the brush and not necessarily use it. Otherwise managing a later initialization is best.

**Comment by alexheretic** [comment]
I guess I want to avoid people just constructing in an obvious way `Builder::new().build()` and then getting a panic later. It's surprising this way.

But maybe we could have `GlyphBrushBuilder::without_fonts()` with suitable doc warnings that if you use a `GlyphBrush` without any fonts it'll panic. This way it should be less surprising to new users.

**Comment by chinedufn** [comment]
Thanks for the context - how does this look?

https://github.com/chinedufn/glyph-brush/commit/b520f524bf556c7daf67719fb517bdb2ecbe7ed4
