### ISSUE TITLE
Changing alpha and colour at the same time does not change the colour

### ISSUE THREAD

**Issue by Ryan1729** [alexheretic/glyph-brush#88]
Currently `glyph_brush` does not allow changing the alpha and the colour of text at the same time, if the text itself does not change.

[Here's a gist](https://gist.github.com/Ryan1729/4cc66eb26f28e81d52cc3ac8d71cf8a5) containing a small change to the example that demonstrates this.

In that version, the alpha changes continuously, and typing anything should toggle the text to be either colourful or grayscale. But the colours remain unchanged. If you comment out line 231 where the `alpha` variable is incremented, then the colour toggling works as expected.

After doing a bit of digging, I found that changing the colour and the alpha at the same time results in the `SectionHashDetail`s that get passed to the `diff` method having identical `geometry` and `text_no_color_alpha` field values, but different values in all the other fields. In the [current implementation of the `diff` method](https://github.com/alexheretic/glyph-brush/blob/fc1a24dc4bd222f65dba44392e8d852e71642433/glyph-brush/src/glyph_brush.rs#L625-L636) this results in `SectionHashDiff::AlphaChange` being returned, which, of course, results in only the alpha changing.

If I change the `diff` method to return `SectionHashDiff::ColorChange` where it previously returned `SectionHashDiff::AlphaChange` then everything seems to work, since the colour includes the alpha value. But, I'm not sure whether there would be other effects elsewhere, or if that would adversely affect performance in important cases.

**Comment by alexheretic** [comment]
Thanks for the example. This looks like a bug, I'll investigate why color changes are triggering only `AlphaChange`.

**Comment by alexheretic** [comment]
Thanks for the working example showing the issue. I've made a fix #92 does this work ok for you?

**Comment by Ryan1729** [comment]
Yes, that works great. Thanks for fixing the issue, and for the rest of your work on the library!

**Comment by alexheretic** [comment]
Great! I'll publish a new release of glyph_brush towards the end of the week.
