### ISSUE TITLE
Positioning glyphs based on baseline

### ISSUE THREAD

**Issue by Ploppz** [alexheretic/glyph-brush#94]
I miss a means of positioning glyphs based on any fixed point in glyphs' local space.

Take this example:
![](https://i.imgur.com/ZfAFp1T.png)
The two text segments should be at the same vertical position, but they have different apparent vertical positions because they have different glyphs. The only thing I can know now apparently is the size of glyphs (bounding box).

If there was some way to get the [baseline](https://en.wikipedia.org/wiki/Baseline_(typography)) of a glyph or anything, it would be great. Rather required for most applications I reckon.

**Comment by alexheretic** [comment]
Positioning logic is already relative to the baseline. Two sections with the same screen-y will have the same baseline.

Can you provide a simple code example showing your usage and what you expect?

**Comment by Ploppz** [comment]
Sorry, you're right.
