### ISSUE TITLE
Pixelated drawing mode

### ISSUE THREAD

**Issue by expenses** [alexheretic/glyph-brush#99]
This is somewhat related to #17, but not entirely. Basically, what I want is a way to render and cache text in a pixelated fashion for pixel art games. The main difference between this and the normal drawing mode is that instead of using a range of alpha values, you round the value to either `0` or `255.`.

An API for this would involve creating a `Mode` enum: 
```rust
pub enum Mode {
    Normal,
    Pixelated { upscale: f32 }
}
```
that goes inside `Section` and `VariedSection`. When it comes to cache the glyphs for this sections, you divide the font size by the `upscale` value, and round the alpha coverage values. The when rendering, you upscale the font again.

I'm interesting in adding this feature myself, but I'm not entirely sure where to put the caching and rendering code.

**Comment by alexheretic** [comment]
I would implement this in the fragment shader. You have an 8-bit coverage alpha there, it can be rounded without any modification to glyph-brush.

**Comment by expenses** [comment]
@alexheretic .... Oh yeah.. :P Closing for now.
